[package]
name = "substreams-ens-pb"
version = "0.1.0"
edition = "2021"
description = "Protobuf definitions for ENS substreams"

[dependencies]
prost = "=0.13.5"
prost-types = "=0.13.5"

[build-dependencies]
prost-build = "=0.13.5"
