[package]
name = "erc20"
version = "1.0.0"
description = "ERC-20"
edition = "2021"
authors = [
    "Denis <denis@pinax.network>",
    "Yaro <yaro@pinax.network>",
    "Matthieu Vachon <https://github.com/maoueh>",
]

[lib]
crate-type = ["cdylib"]

[dependencies]
ethabi = "18.0"
hex = "0.4.3"
hex-literal = "0.4"
prost = "0.13"
prost-types = "0.13"
num-bigint = "0.4"
substreams = "0.6"
substreams-ethereum = "0.10"
substreams-entity-change = "2.0"
substreams-database-change = "2.0"
num-traits = "0.2.16"

[build-dependencies]
prost-build = "0.13"
anyhow = "1"
substreams-ethereum = "0.10"
