[workspace]
members = [
  "erc20-balances",
  "erc20-balances-rpc",
  "erc20-contracts",
  "erc20-contracts-rpc",
  "native-balances",
  "native-contracts",
  "uniswap-v2",
  "uniswap-v3",
  "proto",
  "common",
  "clickhouse"
]
resolver = "2"

[workspace.package]
description = "EVM Tokens"
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
substreams = "0.6"
substreams-abis = "0.1.3"
substreams-ethereum = "0.10"