[workspace]
members = [
  "erc20",
  "erc20-rpc",
  "contracts",
  "native",
  "proto",
  "common",
  "prices",
  "clickhouse"
]
resolver = "2"

[workspace.package]
description = "EVM Tokens"
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
substreams = "0.6"
