[workspace]
members = [
  "erc20",
  "erc20-rpc",
  "erc20-contracts",
  "erc20-contracts-rpc",
  "native",
  "prices-uniswap-v2",
  "proto",
  "common",
  "clickhouse"
]
resolver = "2"

[workspace.package]
description = "EVM Tokens"
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
substreams = "0.6"
substreams-abis = "0.1.3"
substreams-ethereum = "0.10"