[workspace]
members = [
  "erc20",
  "contracts",
  "native",
  "proto",
  "common",
  "evm-tokens",
  "subgraph",
]
resolver = "2"

[workspace.package]
description = "EVM Tokens"
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
substreams = "0.6"
