[package]
name = "erc20-balance-changes"
version = "0.0.0"
description = "ERC-20"
edition = "2021"
authors = [
    "Denis <denis@pinax.network>",
    "Yaro <yaro@pinax.network>",
    "Matthieu Vachon <https://github.com/maoueh>",
]

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.13"
prost-types = "0.13"
substreams = "0.6"
substreams-ethereum = "0.10"
substreams-abis = "0.1"
substreams-entity-change = "2.0"
substreams-database-change = "2.0"
