[workspace]
members = [
  "erc20-balances",
  "clickhouse",
  "subgraphs",
]
resolver = "2"

[workspace.package]
description = "ERC-20 Balances"
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
substreams = "0.6"
