[package]
name = "proto"
description = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
prost = "0.13"
prost-types = "0.13"
# substreams = { workspace = true }
# substreams-ethereum = "0.10"
# substreams-abis = "0.1"
