[package]
name = "common"
description = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
substreams = { workspace = true }
substreams-database-change = "2.0"
prost = "0.13"
prost-types = "0.13"
