[package]
name = "substreams-ens"
version = "0.2.0"
edition = "2021"
description = "ENS Substreams implementation"

[dependencies]
prost = "=0.13.5"
prost-types = "=0.13.5"
substreams.workspace = true
substreams-ethereum.workspace = true
substreams-ens-pb = { path = "./substreams-ens-pb" }
ethabi = "18.0.0"
hex = "0.4"

[build-dependencies]
prost-build = "=0.13.5"
substreams-ethereum.workspace = true
anyhow = "1.0"

[lib]
name = "substreams_ens"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
